package entities;
// Generated Nov 22, 2017 11:02:05 AM by Hibernate Tools 4.3.1



/**
 * BillDetail generated by hbm2java
 */
public class BillDetail  implements java.io.Serializable {


     private Integer id;
     private int billId;
     private int productId;
     private double price;
     private int quantity;

    public BillDetail() {
    }

    public BillDetail(int billId, int productId, double price, int quantity) {
       this.billId = billId;
       this.productId = productId;
       this.price = price;
       this.quantity = quantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getBillId() {
        return this.billId;
    }
    
    public void setBillId(int billId) {
        this.billId = billId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


