package entities;
// Generated Nov 22, 2017 11:02:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set productsForCatid = new HashSet(0);
     private Product productById;

    public Category() {
    }

	
    public Category(String name) {
        this.name = name;
    }
    public Category(String name, Set productsForCatid, Product productById) {
       this.name = name;
       this.productsForCatid = productsForCatid;
       this.productById = productById;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProductsForCatid() {
        return this.productsForCatid;
    }
    
    public void setProductsForCatid(Set productsForCatid) {
        this.productsForCatid = productsForCatid;
    }
    public Product getProductById() {
        return this.productById;
    }
    
    public void setProductById(Product productById) {
        this.productById = productById;
    }




}


