package entities;
// Generated Nov 22, 2017 11:02:05 AM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private Category categoryByCatid;
     private Category categoryById;
     private String name;
     private String image;
     private double price;
     private String description;

    public Product() {
    }

    public Product(Category categoryByCatid, Category categoryById, String name, String image, double price, String description) {
       this.categoryByCatid = categoryByCatid;
       this.categoryById = categoryById;
       this.name = name;
       this.image = image;
       this.price = price;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategoryByCatid() {
        return this.categoryByCatid;
    }
    
    public void setCategoryByCatid(Category categoryByCatid) {
        this.categoryByCatid = categoryByCatid;
    }
    public Category getCategoryById() {
        return this.categoryById;
    }
    
    public void setCategoryById(Category categoryById) {
        this.categoryById = categoryById;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


